### PR TITLE
Search Material-Table, OurRoots API

### PR DESCRIPTION
**Pull request by judyichiang**

### CODE REVIEW

**Comment by judyichiang** [comment]
Hello, 
- Added CORS support to API proxy
- OurRoots data can be pulled to the Material-Table

But problems I have been encountering and trying to resolve 
1) popover/checkbox values disappear when the modal is hidden. 
2) onChange in react-hook-forms, this was used for the CheckBox component- should I try adding this to a render prop?
https://react-hook-form.com/api/#Controller
3) click table row to open another Details component, I was trying out the details panel while trying to make the entire row click to open another component or link.

**Comment by judyichiang** [comment]
4) also looking into how to add multiple fields in a material-table, for example for address, right now i can only add one key value : city, street, states, etc.

**Comment by RobertGardner** [comment]
Some comments to the problems you were looking into:

1. I found when working with modals that the state variables retain their values even when the modal is hidden. This can be confusing if you are expecting it to reset them when it is shown. If that's what you need, there are techniques I can show you for detecting if properties have changed (which may indicate you want to reset state).

2. In my Material-UI project using a checkbox and controller, I do the following:
   `onChange={([, checked]) => checked}`
(I'm not sure this addresses your question, which I don't fully understand.)

3. I haven't tried clicking an entire row in material-table. I use the icon actions. They look nice and are effective.

4. There are several ways to add a column that displays data from multiple fields. The best is probably to use the `render` field in the header definition. You specify a function that takes the entire row as input and returns a JSX.Element. Something like this:
`{ field: 'addr', title: 'Address', render: address }`
```
function address(row: Data): JSX.Element {
  return <Typography>{row.street}, {row.city}, {row.state}</Typography>;
}
```

**Comment by judyichiang** [comment]
I'm still having  problem with the modal values disappearing when the modal is hidden- help on this would be great!

And I made a pr and merged it, the Data Fetching component is direct axios to material-table. Here the data can be added to the table

datafetch

but on useSearch, I haven't been able to add Material-table. 
with axios I can use res.hits to get the values needed, but with useSearch
datahits

useSearch

searchresultstable

**Pull request merged**
